### ISSUE TITLE
Infinite Dimensions 1.5.4 (January 30 2024) bugs

### ISSUE THREAD

**Issue by Gomaworm** [LeraRiemann/ProjectInfinity#1]
I was just playing infinite dimensions 1.5.4 (January 30 2024), and I have two bugs I'd like to report:
(1) I made a nether portal and threw in an unsigned book with a 5 letter word. The portal changed color like it should. When I tried to enter in either survival mode, it would do the swirling portal animation as normal and then leave me in the overworld. Creative mode, signed books, new portals, and different words did not make a difference. I tried some in-game debugging of my own, and managed to be able to use them in a weird, roundabout way. In the overworld, after throwing a book to set a destination, I threw an ender pearl through the portal and it landed on the other side of the portal still in the overworld. After a successful pearl teleport, I could walk through and use the portal both ways between dimensions as intended, until I threw in a new book. One time the pearl never landed, so I never teleported, and I still couldn't get to another dimension. Hopefully this helps in you debugging.
(2) The game crashed in one of the dimensions as is typical of the infinity snapshot, and, based on the error description, I believe I simply need to allocate more RAM to Minecraft and reduce my simulation/render distances. I will attach the Modrinth error log below, in case any information is relevant. I used Fabric-API 0.91.0+1.20.1, since Modrinth required Fabric API to run the mod.
[Error Log.txt](https://github.com/LeraRiemann/ProjectInfinity/files/14106883/Error.Log.txt)
Thank you for making on this mod. The 20w14infinite April Fools update is my favorite, but it is a few versions behind.

**Comment by Gomaworm** [comment]
Update: To update the portal color, after throwing in a new book, I have to stand in the portal and unsuccessfully teleport. The ender pearl workaround only works once the portal color has updated. Also, I installed sodium and I haven't run into any crashes or lag the last hour of playtime.

**Comment by LeraRiemann** [comment]
properly updating a portal color with a new book is sadly not yet implemented, so no worries

about the unable to teleport thing. have you tried right clicking the portas right after you throw the book byt before you step in? that's the intended way if solving that issue. does it work?

**Comment by Gomaworm** [comment]
Right clicking worked great! Apparently throwing ender pearls at the portal was technically right clicking the portal. LOL. I probably would have figured it out if I carefully read the wiki, which I am doing now. Thank you for the mod and I look forward to further improvements.
