### ISSUE TITLE
Memory Leak + Text?

### ISSUE THREAD

**Issue by Dumpling00** [LeraRiemann/ProjectInfinity#14]
Hello again! Been messing a few with infinite dimensions and I had a few questions from a couple of thigns I've noticed.

1. I normally play with 10GB of RAM allocated. After opening a second dimension I've started noticing huge lag spikes and no longer after that, my game crashed. I upped the memory and tried again, and I've noticed that for each new dimension, the memory usage goes up 1GB or so. Is this something that can be optimized at all, or is the nature of the mod only gonna allow for so many dimensions until the game becomes eventually unsustainable?

2. With almost every dimension I've visited, I'm finding some sort of floating text like in the picture. I'm wondering if there are any plans to get rid of those since in my opinion, really take away from the immersion.
![image](https://github.com/LeraRiemann/ProjectInfinity/assets/44829013/7e01c4e5-635a-4b50-8d2f-e8a73c085c67)

Thank you for your time!

**Comment by LeraRiemann** [comment]
On the RAM, I don't think I encountered that problem before - and I've been hopping dimensions in dozens per session. That said, I remember you are playing a large modpack, so it may be an obscure mod interaction that's causing this. I won't be able to patch that with so little detail on the issue.

About text: it's a feature, but one I, and even you yourself, can easily reduce the ubiquity of by lowering the random chance value for generating them in config/infinity/infinity.json (you can even set it to 0 to disable the generation entirely). I can lower the _default_ chance for them in the next update if you want.

**Comment by Dumpling00** [comment]
> On the RAM, I don't think I encountered that problem before - and I've been hopping dimensions in dozens per session. That said, I remember you are playing a large modpack, so it may be an obscure mod interaction that's causing this. I won't be able to patch that with so little detail on the issue.
> 
> About text: it's a feature, but one I, and even you yourself, can easily reduce the ubiquity of by lowering the random chance value for generating them in config/infinity/infinity.json (you can even set it to 0 to disable the generation entirely). I can lower the _default_ chance for them in the next update if you want.

Thank you! Will be messing with that - also upon more testing, it feels like I've just been unlucky with the generation, as one of the generations had the ground filled with cakes, which I assume was the cause of the spike and eventual crash.
Another crash was dictated by four withers spawning, as for the third one, the terrain generation seemed wacky and likely too much.
Actually - worth mentioning, I'm playing on BetterX Amplified. Something tells me this COULD affect the ram usage of the dimensions. Have they only been tested on default terrain gen?

I'll do more testing on the weekend after streamlining my mod pack and deleting some redundant mods, but more info would be great.

**Comment by Dumpling00** [comment]
I have tried with a Default world and after some optimization, and things seem a bit better, but I've found a dimension where the floor is cake, and my Ram usage practically doubled in a few seconds. From a normal usage of 5GB to 9-10. It would shoot up and then immediately go back to 50% and loop around again.

I also can't seem to turn off the random texts. May I please have some assistance there?
Along with maybe a way to blacklist certain blocks from being used to generate worlds? So far I've found floors covered with cake, pressure plates and shulker boxes, which I believe to be the major culprits when it comes to lag spikes.

Thank you again for your time!

**Comment by LeraRiemann** [comment]
BetterX should have no effect on generation of dimensions as it only affects its own dimensions.

On the topic of cakes and pressure plates on the floor, i believe i can fix this by just forbidding the top layer to be anything that cannot be placed in midair.

**Comment by Dumpling00** [comment]
> BetterX should have no effect on generation of dimensions as it only affects its own dimensions.
> 
> On the topic of cakes and pressure plates on the floor, i believe i can fix this by just forbidding the top layer to be anything that cannot be placed in midair. As the problem with cakes is probably them block-updating and breaking en masse when there's nothing underneath.

On that same front, I've had another stroke of bad luck with a dimension where the ceiling seemed to be made of gravel, sand, or another gravity-influenced block. Everything started collapsing and the lag was massive lol
But yeah sounds good!

**Comment by LeraRiemann** [comment]
As of the version 1.9.1 of the mod, i believe both sand on the ceiling and unstable cakes/pressure plates/etc to be prevented from generating. I also brought the default chance of text generating from 50% to 10%.

Don't forget to purge the config folder for these changes to apply.
