### ISSUE TITLE
game crashes after word loading on 1.10.2

### ISSUE THREAD

**Issue by lnee94** [LeraRiemann/ProjectInfinity#17]
This only effects that version so far as I know I tested 1.10.1.
Replacat load minecraft create new world and wait for it to load and it crashes
Link to log https://mclo.gs/bmzzI5x

Cool project I deffenity want to use this in a mod pack
If there is anything I can do to help give me a call

**Comment by LeraRiemann** [comment]
this crash should be fixed as of 1.10.3 of the mod.

**Comment by lnee94** [comment]
yep this crash is fixed though I think there are others I will get back to you on that after more testing

**Comment by lnee94** [comment]
ok good
