### ISSUE TITLE
Please do Forge version if possible

### ISSUE THREAD

**Issue by TM-yt** [LeraRiemann/ProjectInfinity#18]
Most mods are made for Forge, including some of my favorite mods, and some of these favorites are forge exclusive.
Please consider doing a forge version

**Comment by lnee94** [comment]
Try it with Sinytra Connector https://modrinth.com/mod/connector first

**Comment by lnee94** [comment]
ok does not work

**Comment by AlfonixJohnson** [comment]
i would also like a forge

**Comment by LeraRiemann** [comment]
Forge version is planned, but most probably it will only come in a very distant future, as it requires a lot of recoding.
That being said, someone reported Sinytra actually half-working very recently probably due to its own updates, so maybe full compatibility will eventually come through this way?

**Comment by LeraRiemann** [comment]
Cassian made a NeoForge version for 1.21! (they're cool)
i think this fulfills the idea! for 1.21 and up there's really no use in non-neo forge, everything forge is moving to neo
