### ISSUE TITLE
Entering portal does nothing

### ISSUE THREAD

**Issue by PickledSosig** [LeraRiemann/ProjectInfinity#2]
Throwing a written and signed book into a portal changes its color, but the resulting portal does not send me anywhere. It plays the portal travel audio and loads for a split second before immediately placing me back inside the portal.

Game Ver: 1.20.1
Fabric Launcher Ver: 0.15.6-1.20.1
API Ver: 0.91.0+1.20.1

Edit: Resolved

**Comment by LeraRiemann** [comment]
have you tried right clicking the portal before entering? if you had not, this is intended behaviour.
