### ISSUE TITLE
Easter egg dimensions dont function and just take me to a random one.

### ISSUE THREAD

**Issue by bobqwertyuiopkj** [LeraRiemann/ProjectInfinity#20]
tried updated and deleting config, and using official modpack and i cant get them to work.

**Comment by LeraRiemann** [comment]
what version of the mod (and modpack) are you using?

**Comment by bobqwertyuiopkj** [comment]
The newest version of mod and modpack, with no changes.

**Comment by tylerb153** [comment]
`/warp` appears to work for example `/warp library` takes you to the library dimension they appear to be inaccessible from the book portal method as a new dimension appears to always be generated

**Comment by cassiancc** [comment]
Are you signing the book? The current version of the mod creates a different seed when the book is signed. I've added a fix in https://github.com/LeraRiemann/ProjectInfinity/pull/21.
