### ISSUE TITLE
Safe Mode Popup when exiting and reopening a world (1.7.2/1.10.4)

### ISSUE THREAD

**Issue by TheLemon27** [LeraRiemann/ProjectInfinity#23]
I was playing the 1.7.2 version on another computer (i think, I'm not at the computer right now so i cant be 100% sure, will edit when i can say for sure) and decided to transfer the world to a different computer. I downloaded the latest version of the mod (1.10.4 at the time of writing) and entered the world. It loaded up fine, and after a bit of messing around and building stuff in my base, I make a new portal and go into it. It doesn't take me to a new dimension. It just does the swirly portal animation without taking me there. I decide to close out of the world and reopen it, maybe that would fix it. when I try to reopen it, the following message is displayed on my screen: "Errors in the currently selected data packs prevented the world from loading. You can either try to load it with only the vanilla data pack ("safe mode"), or go back to the title screen and fix it manually." The only options are [Safe mode] and [Back to Title Screen].
Can someone please help? Thanks in advance!

**Comment by LeraRiemann** [comment]
You somehow generated a broken datapack, probably because you haven't updated the mod correctly (you have to purge mod's config files when updating).

Can you include your game log?

**Comment by TheLemon27** [comment]
Yeah, I didn't know you had to do that, I just replaced the jar file (you should probably say that on the mods' page).

Here's the last log file that was generated.
[latest.log](https://github.com/LeraRiemann/ProjectInfinity/files/15026605/latest.log)

Also, would it be safe for me to purge the config files now or would that have unintended consequences?

**Comment by LeraRiemann** [comment]
sorry for long absence, the mod development went on hiatus for a while.
have you managed to fix it?

purging configs should always be fine as they regenerate on every launch if deleted.
also, your latest.log should contain a reference to which world exactly is broken, that way you can find and delete the appropriate datapack.

**Comment by TheLemon27** [comment]
I'm so sorry that I didn't respond sooner.

I never fixed the issue, I just continued using the old version for that world.
(closed as not planned, because 1: i didnt solve it and 2: this is a bit of a stale issue)

**Comment by TheLemon27** [comment]
ok, im trying to use the up-to-date versions of the mod now, and I just wanna ask a question related to this.

if i have a world where ive never opened a dimensional portal, but still had the mod installed when creating/playing in it, will i still have to delete a datapack? or are datapacks only generated when a dimension is created?
