### ISSUE TITLE
Version Problem

### ISSUE THREAD

**Issue by Feelbros** [LeraRiemann/ProjectInfinity#27]
̷T̷h̷e̷ ̷b̷o̷o̷k̷s̷ ̷d̷o̷n̷'̷t̷ ̷w̷o̷r̷k̷,̷ ̷t̷h̷e̷ ̷c̷o̷l̷o̷u̷r̷ ̷o̷f̷ ̷t̷h̷e̷ ̷p̷o̷r̷t̷a̷l̷ ̷c̷h̷a̷n̷g̷e̷s̷ ̷a̷s̷ ̷i̷t̷ ̷s̷h̷o̷u̷l̷d̷,̷ ̷b̷u̷t̷ ̷I̷ ̷d̷o̷n̷'̷t̷ ̷t̷e̷l̷e̷p̷o̷r̷t̷ ̷t̷o̷ ̷t̷h̷e̷ ̷n̷e̷w̷ ̷d̷i̷m̷e̷n̷s̷i̷o̷n̷.̷ ̷
![nothing happens](https://github.com/LeraRiemann/ProjectInfinity/assets/169448885/115122b2-9af8-41e3-a068-33eed7702ccd)

 ̷I̷'̷v̷e̷ ̷t̷r̷i̷e̷d̷ ̷i̷n̷f̷i̷n̷i̷t̷y̷-̷1̷.̷1̷0̷.̷4̷-̷1̷.̷2̷0̷.̷1̷ ̷a̷n̷d̷ ̷i̷n̷f̷i̷n̷i̷t̷y̷-̷1̷.̷1̷0̷.̷3̷-̷1̷.̷2̷0̷.̷1̷,̷ ̷i̷t̷'̷s̷ ̷t̷h̷e̷ ̷s̷a̷m̷e̷!̷

 ̷I̷f̷ ̷I̷ ̷w̷r̷i̷t̷e̷ ̷/̷w̷a̷r̷p̷ ̷a̷n̷d̷ ̷n̷a̷m̷e̷s̷ ̷i̷t̷'̷s̷ ̷f̷i̷n̷e̷.̷
But if I write /warp (inside another warp) it does not work.

 ̷s̷o̷ ̷i̷ ̷w̷a̷n̷t̷ ̷u̷s̷e̷ ̷d̷i̷m̷e̷s̷n̷i̷s̷o̷n̷ ̷i̷n̷ ̷s̷u̷r̷v̷i̷v̷a̷l̷ ̷a̷n̷d̷ ̷i̷ ̷c̷a̷n̷'̷t̷ ̷:̷(̷

**and one more** if i use easter egg warps like: /warp ant e.t.c it doesn't work

but /warp library working.

THANK YOU FOR YOUR WORK < 3 and please fix it 

**With the first problem, I didn't click the right mouse button) but all the others remain**  

_### and how about achievment?_
![new achievment](https://github.com/LeraRiemann/ProjectInfinity/assets/169448885/b23204ef-b6fc-4d7d-8fa5-16593a069c7c)

**Comment by cassiancc** [comment]
So, not all easter egg dimensions from 20w14infinite are in the mod. The ant dimension isn't available in the main mod. You can try out the Ant dimension in 1.20 with the [Infinity Plus](https://modrinth.com/modpack/infinity-plus) modpack, which adds some extra dimensions.
This achievement has been lowered to opening 100 portals, and not 1,000,000,000, as to make it actually achievable.

**Comment by LeraRiemann** [comment]
works as intended
