### ISSUE TITLE
Modded Blocks don't show up in dimensions by default

### ISSUE THREAD

**Issue by CoolHenry22** [LeraRiemann/ProjectInfinity#28]
I installed some mods hoping to get themin the dimension, but they are not there! I don't have time to use the config, so could they be enabled by default?

**Comment by cassiancc** [comment]
The configuration for modded blocks is automatically generated after right clicking a Transfinite Altar with a Diamond. The altar can be crafted by thowing a Lectern into an Infinity Portal.

**Comment by LeraRiemann** [comment]
works as intended i guess

**Comment by LeraRiemann** [comment]
oh. also 1.11.0 of the mod fixes this for real :D now you don't need the altar anymore
