### ISSUE TITLE
Incompatibility with immersive portals and qouteall gravity changer

### ISSUE THREAD

**Issue by VioletSkies19** [LeraRiemann/ProjectInfinity#39]
if this is installed alongside qouteall gravity changer, the game crashes on startup.
if installed alongside immersive portals, the grame crashes when loading a new dimension for the first time. You can reload the world afterwards and everything works normally.

**Comment by TheLemon27** [comment]
OH! THAT"S why it was crashing!

It works fine if you use an older version (i use ver 1.7.2)
but I do think that should be remedied.

As for immersive portals, I'm surprised it works at all lol. I thought the book would just pass through.

**Comment by VioletSkies19** [comment]
> As for immersive portals, I'm surprised it works at all lol. I thought the book would just pass through.

it does on the immersive portals, but you can still light normal portals when you have immersive portals installed

**Comment by TheLemon27** [comment]
> > As for immersive portals, I'm surprised it works at all lol. I thought the book would just pass through.
> 
> it does on the immersive portals, but you can still light normal portals with shift when you have immersive portals installed
Ah! i didnt know that!

**Comment by cassiancc** [comment]
Gravity Changer compatibility will be included in an upcoming version of Infinite Dimensions for 1.20. Immersive Portals support is also possible, but will take more time.
