### ISSUE TITLE
Better config for the new versions?

### ISSUE THREAD

**Issue by TheLemon27** [LeraRiemann/ProjectInfinity#40]
Hi, I really like this mod. However, I've found myself getting annoyed by the chaos pawns, chaos slimes and other new additions.

Would you be willing to add some extra settings for enabling/disabling the new additions (maybe even mod menu support?), or can I already do that and I just missed the memo?

Thanks in advance!

**Comment by LeraRiemann** [comment]
mod menu support is planned, yup
a config for disabling new mobs... i just had an idea on how such a toggle might be implemented, but it may be somewhat stupid, will try and see

**Comment by TheLemon27** [comment]
no yeah all I meant by "new additions" was the mobs.

i see you added a toggle in the latest version. im not gonna close this yet because you labelled it as "experimental', and I havent tested it yet

**Comment by cassiancc** [comment]
With Mod Menu support now integrated, I'm closing this unless an issue is found with the implemented toggle.
