### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Qytexuu** [LeraRiemann/ProjectInfinity#41]
Please please please, how do you update this to 1.21, any brief explanation would be great I don’t want to downgrade to 1.20.1 if you could just provide instructions on how to update to 1.21 that would be awesome

**Comment by LeraRiemann** [comment]
You cannot.

**Comment by LeraRiemann** [comment]
i updated it!! :3

**Comment by Qytexuu** [comment]
You are awesome!
