### ISSUE TITLE
Possible issue relating to payload size or smth

### ISSUE THREAD

**Issue by KenanTheFab** [LeraRiemann/ProjectInfinity#46]
https://mclo.gs/O4ngy40

Think my world is completely bricked as I am completely unable to enter it after playing with inf dimensions. Portals usually crashed no matter what but I'd spawn in the generated dimension after reloading the world (with or without the runtime generation setting on.)

Tried disabling mods like distant horizons and immersive portals to see if that was the issue but yeah. If nothing else I hope the bug report above has something of note.

**Comment by LeraRiemann** [comment]
i think you have a bugged datapack generated by the mod? but it seems like your modpack configuration handles bugged datapacks differently so i'm not sure if my guess is correct.
try removing the datapack by the name generated_962733733? maybe this unbricks it

**Comment by LeraRiemann** [comment]
oh
sorry
i see the payload thing
hmm...
i do indeed use very large packets, but i never thought this to be an issue
looks like your modpack doesn't like it
i can look into splitting my packets a bit

**Comment by LeraRiemann** [comment]
aaand they are split in the latest commit
if you'd like, you can join the discord so i can send you this development build early so you can test if this fixed your issue, otherwise this will be part of the next mod update!

**Comment by KenanTheFab** [comment]
I prefer not to join discords all willy nilly so I'll wait for the release and get back to you if that is okay. I am excited to see the next release and hope for a less crash prone generation.

**Comment by LeraRiemann** [comment]
1.12.2 of the mod just released incorporating this change. can you check?

**Comment by KenanTheFab** [comment]
> 1.12.2 of the mod just released incorporating this change. can you check?

https://mclo.gs/i1QrsMp Save is still bricked and inaccessible with a payload message.

**Comment by LeraRiemann** [comment]
i looked through both crash logs one more rime and have to ask.
have you ever _removed_ mods from this save?

**Comment by KenanTheFab** [comment]
> i looked through both crash logs one more time and have to ask. have you ever _removed_ mods from this save? there are calls of not being able to find blocks from seasonsextras, which if im not mistaken is not present in your modpack so the only possible explanation for it being called for is that it was present at one point

It is present, whenever I edit my mod selection I tend to make a new world for safety- although I *did* remove it for testing (as it did appear in error logs when loading the bricked savefile but the issue persisted with or without it enabled.) which changed nothing- same error each time, payload too big.

with seasonsextras enabled and error is the same.
https://mclo.gs/dA2aZyx

**Comment by LeraRiemann** [comment]
i recommend you to generate not only a new world, but new config files as well each time you edit and especially delete mods. (by deleting the config/infinity folder, it will generate anew on next launch)
for unbricking a save, you may also try deleting all datapacks on it (essentially removing all custom dimensions from being loaded)
other than that i can't think of anything else that might help, sorry >< in such a heavily modded environment as yours i don't properly understand what the logs are trying to say
