### ISSUE TITLE
Throwing [Book and Quill] Item Into Nether Portal Crash the Game and Makes SaveFile UnLoadAble

### ISSUE THREAD

**Issue by Horizoll** [LeraRiemann/ProjectInfinity#47]
Fabric 1.21.1

**Comment by LeraRiemann** [comment]
Please provade the logs - for the crash part and for a game session where you try to open the unloadable file

**Comment by Horizoll** [comment]
[crash-2024-10-03_11.39.08-server.txt](https://github.com/user-attachments/files/17240422/crash-2024-10-03_11.39.08-server.txt)[crash-2024-10-03_11.46.41-server.txt](https://github.com/user-attachments/files/17240421/crash-2024-10-03_11.46.41-server.txt)

**Comment by LeraRiemann** [comment]
are you throwing an empty book and quill or does it have text in it? the crash suggests the first

**Comment by Horizoll** [comment]
Yes, I occasionally threw empty book and quill into nether portal

**Comment by LeraRiemann** [comment]
okay then i think i know exactly what is wrong! will fix it once i'm home ^^

**Comment by LeraRiemann** [comment]
should be fixed in 1.12.4 of the mod! let me know if it is!

**Comment by syntience** [comment]
i had a similar thing happen in 1.20.1, mod version 1.11.1, after throwing a book from the library dimension into a portal
[crash-2024-10-07_17.10.58-server.txt](https://github.com/user-attachments/files/17284585/crash-2024-10-07_17.10.58-server.txt)
error log after trying to join world: https://mclo.gs/jYeElrj

**Comment by LeraRiemann** [comment]
smells interesting
"not a number: 245L" why is it trying to write a long down huh
will try to fix this once home! though this fix will be in a 1.21.1 version

**Comment by LeraRiemann** [comment]
actually

it fails to parse _noise settings_ so most probably there's a biome in one of the mods that has a custom surface rule which contains longs in it! fascinating!

yeah i know exactly how to fix this

for now, you can look what biome's causing this and disable it manually (if you don't know how, you can send me the datapack that causes this error and i'll sniff it out for you)

**Comment by syntience** [comment]
> though this fix will be in a 1.21.1 version

oof sadge, i'll have to update my modpack then

> for now, you can look what biome's causing this and disable it manually (if you don't know how, you can send me the datapack that causes this error and i'll sniff it out for you)

would i be able to send a modrinth export of the modpack? also how do you want me to send it to you?

thanks for looking into it!

**Comment by LeraRiemann** [comment]
Should be fixed in 1.13.0 which just released. Before checking if the fix worked, please backup&delete config/infinity/modular and let it regenerate: it most probably had broken files in it that will be fixed on regeneration.

In terms of what you can send & how: i need a broken datapack from the datapacks folder, if you can't figure out which one's broken you can just archive & send the entire folder, or you can send the config/infinity/modular folder the same way (over discord for example), but if the fix worked it isn't necessary.

**Comment by syntience** [comment]
[crash-2024-10-12_18.15.41-server.txt](https://github.com/user-attachments/files/17351690/crash-2024-10-12_18.15.41-server.txt)
i also had this crash. same cause as the other one, and also renders a world unloadable
[datapacks.zip](https://github.com/user-attachments/files/17351692/datapacks.zip)
and here's the datapack folder from one of these worlds

**Comment by cassiancc** [comment]
Multiple bugs ended up being reported in this issue, but should all be resolved now. A new issue should be opened if a new bug is found.
