### ISSUE TITLE
Some easter egg dimensions are bugged

### ISSUE THREAD

**Issue by TVFLabs** [LeraRiemann/ProjectInfinity#49]
Well, first I would like to say thank you so much for making this mod. I loved 20w14infinite and I'm so glad I can play an upgraded version of it on modern versions. Anyway, here's the bug report:

The dimensions in question are `checkerboard` and `forest`. Interestingly, `chess` works fine and brings me to the dimension that the wiki says `checkerboard` is meant to take you to.
When using the `/warp` command with either, the game prints "An unexpected error occurred when trying to execute that command" to the chat and does not take me to the dimension, and any future uses of the `/warp` command (with any string) will have the same result until I reload the world in safe mode.
When throwing a book and quill into a portal with either, the game just crashes.
When attempting to load a world after doing either, the game brings me to the "Errors in currently selected data packs prevented the world from loading" screen. If I choose safe mode, 1 of 2 things happens: the game loads normally if I had used `/warp`, but it crashes if I had thrown a book and quill. 
These things happen on the latest release (2.0.2+1.21.1) on both Fabric and NeoForge.

This is the crash report I get when throwing a book and quill with the text "checkerboard" into a nether portal, using NeoForge and the latest release of the mod: [crash-2024-10-31_13.26.52-server.txt](https://github.com/user-attachments/files/17591140/crash-2024-10-31_13.26.52-server.txt)
And this is the crash report I get when doing the same but with the text being "forest": [crash-2024-10-31_13.33.44-server.txt](https://github.com/user-attachments/files/17591267/crash-2024-10-31_13.33.44-server.txt)

**Comment by LeraRiemann** [comment]
hi!

checkerboard was recently renamed to chess and i didn't command the game to clear the old file out, as i thought to implement a different checkerboard over the old one later but forgot - my bad! i'll do this new checkerboard in one of the next patches which will hopefully fix it.

with the forest, it was also recently renamed (random_forest -> forest), but i don't immediately see why would that make it crash (with chess i also renamed the biome which is the reason for the crash, with forest i did not). i'll investigate.

for now, starting on a clean instance (deleting all config files and the datapacks for checkerboard and forest) should hopefully stop the crashes. can you test that? if it still crashes that'll be a sign of a bigger problem

**Comment by TVFLabs** [comment]
I deleted the `config/infinity/` folder and the old world. `checkerboard` works fine now (it takes me to a randomized dimension), but `forest` still doesn't. Here's the log: [crash-2024-10-31_14.03.14-server.txt](https://github.com/user-attachments/files/17591563/crash-2024-10-31_14.03.14-server.txt)

**Comment by LeraRiemann** [comment]
peculiar!

the forest is unique in one more aspect, in that the biome file for it is created at runtime (as it needs to incorporate modded trees into itself).

thinking about it now, this was definitely risky to do - it's better to have this biome file bundled and only _replace_ it at runtime. how i did it worked until now, but maybe it broke on Neoforge for some reason?

in any case, i will bundle the default biome file in the next patch! ty for bringing this to my attention ^^

**Comment by TVFLabs** [comment]
Well I just deleted the `config/infinity/` folder and the world once again and tested `forest` on Fabric, and it doesn't seem to work there either. Here's the log I got: [crash-2024-10-31_18.22.44-server.txt](https://github.com/user-attachments/files/17593971/crash-2024-10-31_18.22.44-server.txt)

**Comment by TVFLabs** [comment]
I downloaded the new version, deleted the folder and world, and yes, `forest` works fine when throwing a book and quill into a nether portal or using the `/warp` command. Thank you so much for fixing this so fast, and just generally thank you for making such a great mod!
