### ISSUE TITLE
How to reduce the appearance of mobs ??

### ISSUE THREAD

**Issue by ErkedScreeN** [LeraRiemann/ProjectInfinity#5]
![i3332mage](https://github.com/LeraRiemann/ProjectInfinity/assets/115761812/15adc412-67bf-4a68-9723-0228f56c52fe)
![i123123mage](https://github.com/LeraRiemann/ProjectInfinity/assets/115761812/02380f20-3ab5-4c87-9497-94f536148a69)

I have 15 fps, there are performance mods in my client
Entity Culling, EBE, Sodium, Nvidium and the like and so on
The mod Infinite is very cool !!👍

**Comment by LeraRiemann** [comment]
hrrm.
i never thought about  structures being able to spawn that frequently feom the mob perspective.
will probably reduce the maximum possible density of structures in a future update.

**Comment by LeraRiemann** [comment]
as of Alpha 1.7.2, I consider it fixed as now the structure spacing is capped at 6 chunks minimum.
