### ISSUE TITLE
Aether incompatibility

### ISSUE THREAD

**Issue by FrostedGeulleisia** [LeraRiemann/ProjectInfinity#52]
Quite similar to another now-fixed issue I found here, it seems the mod breaks trying to interpret entities from The Aether mod, for the same reason as in that case: unexpected characters in names. Crash log's provided below
[crash-2024-11-13_21.49.12-server.txt](https://github.com/user-attachments/files/17739211/crash-2024-11-13_21.49.12-server.txt)

**Comment by cassiancc** [comment]
Thanks for reporting this! It has been fixed for the next version of Infinite Dimensions.
