### ISSUE TITLE
Emerging from wrong portal

### ISSUE THREAD

**Issue by wknowleskellett** [LeraRiemann/ProjectInfinity#53]
I had portals to two different dimensions near each other in the overworld, and when I came out of one dimension, I was standing in the other dimension's portal.

Cool mod! I'm using it for reference for my own mod that will have to create dimensions on the fly.

**Comment by cassiancc** [comment]
Thanks for the report! This has been fixed for the next version of Infinite Dimensions.

**Comment by wknowleskellett** [comment]
Badass.

**Comment by LeraRiemann** [comment]
i gotta say i never even considered implementing a feature like this before your report so thank you :D
