### ISSUE TITLE
[Forge 1.20.1] Crash With Terralith

### ISSUE THREAD

**Issue by CraftyZombie** [LeraRiemann/ProjectInfinity#54]
Forge: 47.3.12
Minecraft: 1.20.1
Mod: 2.1.4

Hi there,

First of all, wanna say I love the concept of this mod so much! I appreciate that there are other people who enjoy and want to carry on the legacy of interesting April Fools features.

I'm working with an enormous number of mods, and everything related to accessing the infinite dimensions leads to the error message shown here:
<img width="920" alt="Screen Shot 2024-11-27 at 6 38 21 PM" src="https://github.com/user-attachments/assets/31881193-8549-420b-84ee-1a51b2bce2c9">

I'm wondering if you know what the issue is based on these logs:
https://mclo.gs/2IqP70r (latest)
https://mclo.gs/DGOQsp5 (debug)

Sorry for the limited information, and please let me know if I can help more!

**Comment by CraftyZombie** [comment]
It's Terralith, collecting new logs now

**Comment by CraftyZombie** [comment]
https://gist.github.com/CraftyZombie/e829b8f597430b8b8105bb0fe0f77169

Reason there was no crash before is due to Neruina blocking it.

**Comment by CraftyZombie** [comment]
Firstly, the mod demands Fabric API be installed, so I'm not sure how it would work without Connector.

Second, I tried with all Fabric Mods just now, and the crash still occurs. It's Terralith.

New logs and crash report: https://gist.github.com/CraftyZombie/7f225bd3c07fab2c51946753f164f98f

It appears to be related to a structure block that gets placed in the sky.

**Comment by cassiancc** [comment]
The mod only requires Forgified Fabric API, not Connector. I'll look into the crash though., it seems like it's trying to read data from Terralith that wasn't correctly created.
