### ISSUE TITLE
Crash on Startup with Cinderscapes as of 2.X.X

### ISSUE THREAD

**Issue by anhonestheart** [LeraRiemann/ProjectInfinity#55]
Fabric Loader 0.16.9
Minecraft 1.20.1
Mod Version: 2.1.3 - 2.1.4 - 2.2.0

Just a heads up that version 2.1.3 introduced a crash on startup with Cinderscapes installed and is also present in 2.1.4 and 2.2.0, only Fabric as far as I've tested. The crash is not present on Infinite Dimensions 1.11.1 and below.
Love the mod!

[v2.1.3 crash report.txt](https://github.com/user-attachments/files/17963595/v2.1.3.crash.report.txt)
[v2.1.4 crash report.txt](https://github.com/user-attachments/files/17963596/v2.1.4.crash.report.txt)
[v2.2.0 crash report.txt](https://github.com/user-attachments/files/17963597/v2.2.0.crash.report.txt)

**Comment by cassiancc** [comment]
Thanks for the report! This has been fixed for the next version of Infinite Dimensions.
