### ISSUE TITLE
 Colliding entity with block (jungle_-174328459.json)

### ISSUE THREAD

**Issue by Horizoll** [LeraRiemann/ProjectInfinity#57]
Hi, recently i made a few tries to make a portal, but had a game crash followed by the inability to load the world

There is a Crash Log:
[crash-2024-12-02_01.10.15-server.txt](https://github.com/user-attachments/files/17970232/crash-2024-12-02_01.10.15-server.txt)
There is a Game Log:
[latest.log](https://github.com/user-attachments/files/17970236/latest.log)

**Comment by LeraRiemann** [comment]
ah yes, looks like a structure with a backslash in its name
we found that those tend to crash things with cass just today, there's a fix already, should be included in the next version to release

**Comment by cassiancc** [comment]
Thanks for reporting, should be fixed in 2.3.3.
