### ISSUE TITLE
Reset Charge bug

### ISSUE THREAD

**Issue by cleep5564** [LeraRiemann/ProjectInfinity#60]
1.Lit the Reset Charge
2.Quit the world
3.Open the world,invalid world data or invalid player data may occur

**Comment by LeraRiemann** [comment]
which version of the game and the mod? this is long fixed in 2.3.5

**Comment by LeraRiemann** [comment]
oh i think i now know what this is about
apparently, it was not fixed in the backport
now it should be as of 2.3.8
