### ISSUE TITLE
ModEntities tried to access private class but Failed

### ISSUE THREAD

**Issue by AndrewJP2024** [LeraRiemann/ProjectInfinity#62]
Minecraft 1.20.1
Forge 47.3.11
Mod: 2.3.5

This happens on startup

Exception message: 
> **java.lang.IllegalAccessError**: class **forge.net.lerariemann.infinity.entity.ModEntities** tried to access private field **net.minecraft.world.entity.SpawnPlacements**.f_21750_ (**forge.net.lerariemann.infinity.entity.ModEntities** is in module infinity@2.3.5+1.20.1 of loader 'TRANSFORMER' @17d19538; **net.minecraft.world.entity.SpawnPlacements** is in module minecraft@1.20.1 of loader 'TRANSFORMER' @17d19538)

[crash-2024-12-10_17.38.55-fml.txt](https://github.com/user-attachments/files/18088905/crash-2024-12-10_17.38.55-fml.txt)

**Comment by LeraRiemann** [comment]
seems like an access widener didn't work correctly which is... weird? maybe something changed with what i'm access-widening between 1.20 and 1.21, i'll check

**Comment by cassiancc** [comment]
Thanks for reporting this! This should be fixed in the next release of the backport (likely 2.3.6)
