### ISSUE TITLE
Consistent crashing

### ISSUE THREAD

**Issue by refluxghoul** [LeraRiemann/ProjectInfinity#64]
When using the mod on 1.20.1 Forge, the game crashes after loading into a world. I can run around for a bit before it randomly crashes. I'm using Forgified Fabric API and Architectury.
[crash-2024-12-15_19.41.57-server.txt](https://github.com/user-attachments/files/18143518/crash-2024-12-15_19.41.57-server.txt)
It seems to be related to fish? On another instance I used Bad Mobs to disable fish spawning but it didn't fix anything.

**Comment by LeraRiemann** [comment]
oh no, not my fish :(
i'll investigate

**Comment by cassiancc** [comment]
Can confirm this bug is present and exclusive to Forge 1.20. Working on a fix for the next version.

**Comment by cassiancc** [comment]
Fix has been made for 2.3.8.
