### ISSUE TITLE
Some Kind of ShaderLoader Problem

### ISSUE THREAD

**Issue by AndrewJP2024** [LeraRiemann/ProjectInfinity#66]
Minecraft Forge
Version 2.3.8 for 1.20.1

Errors on join after going throw a portal

[Server.log](https://github.com/user-attachments/files/18159905/Server.log)

**Comment by cassiancc** [comment]
Thanks for reporting this, we've reuploaded 2.3.8 and it should no longer occur. Just redownload the mod, and it should no longer crash.
