### ISSUE TITLE
The Gamerules and A 1.20.4 Version 

### ISSUE THREAD

**Issue by Wilish-World** [LeraRiemann/ProjectInfinity#7]
Hello, thank you for making this mod, me and my friends are enjoying it very much. I just have some questions like where the gamerule commands are because I typed them into the command bar and they're not showing up there nor when I type /gamerule in front of them so I'm a little lost on that. Also, I just wanted to ask if a 1.20.4 version would come out. Thank you for reading this

**Comment by LeraRiemann** [comment]
the gamerules are currently only changeable by editing the config/infinity/infinity.json file directly. as for the 1.20.4 update, it is not a priority since from what i know most modpacks are assembled on 1.20.1?..

**Comment by Wilish-World** [comment]
oh okay, yeah the 1.20.4 thing was mainly just an issue with me trying to combine different mods together for a server but it is very niche. Thanks for answering though.
