### ISSUE TITLE
1.8.0 - Minecraft client always complaining about corrupted data pack at start of world

### ISSUE THREAD

**Issue by MarcusInVR** [LeraRiemann/ProjectInfinity#8]
Since I have 1.8.0 of the mod, I always have to delete the "infinity" folder from [world]/datapacks. It seems that if the content is re-generated on load, it's fine - but launching a world with this data will result in mentioned error message.

Minecraft 1.20.1 - Java - 4G RAM assigned to client - Endeavour OS (Linux distro)

For now I have reverted back to 1.7.2 which did not exhibit this behavior.

**Comment by LeraRiemann** [comment]
Try deleting both datapacks/infinity and config/infinity.
